import { env } from "./env";
import { STELLAR_NETWORK_PASSPHRASE, STELLAR_RPC_URL } from "./stellar-network";

export const STELLAR_CONFIG = {
  RPC_URL: STELLAR_RPC_URL,
  NETWORK_PASSPHRASE: STELLAR_NETWORK_PASSPHRASE,
  ESCROW_CONTRACT_ID: env.ESCROW_CONTRACT_ID,
  AGENT_SECRET_KEY: env.AGENT_SECRET_KEY,
  AGENT_PUBLIC_KEY: env.AGENT_PUBLIC_KEY,
  USDC_TOKEN_ID: env.USDC_TOKEN_ID ?? "",
} as const;
